### PR TITLE
Avoid holding lock while communicating with TFS

### PR DESCRIPTION
**Pull request by snakefoot**
If you could make a release with working dependencies, then it would be great (Don't have to be on market-place)

### CODE REVIEW

**Comment by JapNolt** [comment]
@snakefoot Sorry about the delay. I've been quite busy. I'd be happy to create a release. Just curious, what problem are you trying to fix with this PR?

**Comment by snakefoot** [comment]
> what problem are you trying to fix with this PR?

Right now it takes a "global" lock and then talks with the TFS-server. This "global" lock is also needed, when reacting to redraw events.

This means a TFS-update-event can trigger a refresh against the TFS-server (while holding the global lock), followed by a redraw event that forces Visual Studio to hang (Waiting for the global lock to be released).

**Comment by JapNolt** [comment]
I've noticed VS randomly hanging during rename refactoring. Do you think this will solve that issue?

**Comment by snakefoot** [comment]
> I've noticed VS randomly hanging during rename refactoring. Do you think this will solve that issue?

This PR ensures that it doesn't hold the "global" lock while communicating with the TFS-server, so it should improve the random hanging.

It was because my visual studio was hanging, that I created a minidump, and could see that this plugin was blocking itself.

**Comment by JapNolt** [comment]
@snakefoot I've created a release available at https://github.com/JapNolt/TfsPendingChangesMargin/releases/tag/v1.1.3 Again, sorry for the delay.

**Pull request merged**
